from mfrc522 import MFRC522
import utime
from machine import Pin, SPI, PWM
from ssd1306 import SSD1306_SPI
import framebuf
from time import sleep
'''
RSP Pico  |   RC522
0         |   RST
1         |   SDA
2         |   SCK
3         |   MOSI
4         |   MISO

RSP Pico  |  OLED
16        |  CS
17        |  DC
18        |  SCK
19        |  MOSI
20        |  RST
'''
green = Pin(11, Pin.OUT)
red = Pin(14, Pin.OUT)
servo = PWM(Pin(15))
yellow = Pin(13, Pin.OUT)
b1 = Pin(12, Pin.IN, Pin.PULL_DOWN)
servo.freq(50)
spi = SPI(0, 100000, mosi=Pin(19), sck=Pin(18))
oled = SSD1306_SPI(128, 64, spi, Pin(17),Pin(20), Pin(16))
#oled = SSD1306_SPI(WIDTH, HEIGHT, spi, dc,rst, cs) use GPIO PIN NUMBERS
reader = MFRC522(spi_id=0,sck=2,miso=4,mosi=3,cs=1,rst=0)
green.value(1)
red.value(1)
yellow.value(1)
oled.text("Initialising...", 0,0)
oled.show()
servo.duty_u16(2887)
utime.sleep(1)
servo.duty_u16(int(4885.68))
utime.sleep(2)
green.value(0)
red.value(0)
yellow.value(0)
oled.fill(0)
oled.show()
oled.text("ATM SYSTEM",0,0)
oled.show()
utime.sleep(1.3)
oled.text("Designed by Aura",0,20)
oled.show()
utime.sleep(2)
def man_function():
    
    oled.fill(0)
    oled.show()
    utime.sleep(1)
    oled.text("Place your Card",0,0)
    oled.show()
man_function()
pb=5000
db  = 12576
while True:
    reader.init()
    (stat, tag_type) = reader.request(reader.REQIDL)
    if stat == reader.OK:
        (stat, uid) = reader.SelectTagSN()
        if stat == reader.OK:
            card = int.from_bytes(bytes(uid),"little",False)
            #print("CARD ID: "+str(card))
            oled.text("Place your Card", 0,0)
            oled.show()
            i=0
            j= 0
            p=0
            
            if card == 1430441570:
                print("Hello Paul Aura!")
                green.value(1)
                oled.fill(0)
                oled.show()
                oled.text("Hello Paul!", 0,0)
                oled.show()
                utime.sleep(1)
                oled.fill(0)
                oled.show()
                oled.text("Enter Pin",0,0)
                oled.show()
                green.value(0)
                utime.sleep(1)
                cmd = input("Enter pin: ")
                if cmd == "565":
                    oled.fill(0)
                    oled.show()
                    oled.text("Choose:", 0,0)
                    oled.text("1. Withdrawal", 0,15)
                    oled.text("2. Deposit", 0,30)
                    oled.text("3. Check Balance", 0,45)
                    oled.show()
                    utime.sleep(1)
                    cmd = input("Choose: ")
                    if cmd == "1":
                        print("Enter Amount")
                        oled.fill(0)
                        oled.show()
                        oled.text("Enter Amount:",0,0)
                        oled.show()
                        cmd = input("Amount:")
                        oled.fill(0)
                        oled.show()
                        oled.text(cmd, 0,0)
                        oled.show()
                        utime.sleep(1)
                        if int(cmd) > pb:
                            oled.fill(0)
                            oled.show()
                            yellow.value(1)
                            oled.text("Insufficient",0,0)
                            oled.text("balance!", 0,15)
                            oled.show()
                            utime.sleep(3)
                            yellow.value(0)
                            man_function()
                        else:
                            oled.fill(0)
                            pb = pb - int(cmd)
                            green.value(1)
                            servo.duty_u16(2887)
                            utime.sleep(2)
                            green.value(0)
                            servo.duty_u16(int(4885.68))
                            oled.show()
                            oled.text("Successful!",0,0)
                            oled.text(cmd + " withdrawn",0,20)
                            oled.text("Balance:" + str(pb), 0,40)
                            oled.show()
                            utime.sleep(3)
                            man_function()
                        
                    elif cmd == "2":
                        print("Enter Amount")
                        oled.fill(0)
                        oled.show()
                        oled.text("Enter Amount:",0,0)
                        oled.show()
                        cmd = input("Amount:")
                        oled.fill(0)
                        oled.show()
                        oled.text(cmd, 0,0)
                        pb = pb + int(cmd)
                        green.value(1)
                        servo.duty_u16(2887)
                        utime.sleep(2)
                        green.value(0)
                        servo.duty_u16(int(4885.68))
                        oled.show()
                        utime.sleep(1)
                        oled.fill(0)
                        oled.show()
                        oled.text("Successful!",0,0)
                        oled.text(cmd + " Deposited",0,20)
                        oled.text("Balance:" + str(pb), 0,40)
                        oled.show()
                        utime.sleep(3)
                        man_function()
                    elif cmd == "3":
                        print("Your Current Balance: Ksh." + str(pb))
                        oled.fill(0)
                        oled.show()
                        oled.text("Current Balance:", 0,0)
                        oled.text("Ksh." + str(pb), 0,15)
                        oled.show()
                        utime.sleep(3)
                        man_function()
                    else:
                        print("Invalid choice")
                        oled.fill(0)
                        yellow.value(1)
                        oled.show()
                        oled.text("Invalid",0,0)
                        oled.show()
                        utime.sleep(3)
                        yellow.value(0)
                        man_function()
                else:
                        print("Wrong pin, try again!")
                        red.value(1)
                        oled.fill(0)
                        oled.show()
                        oled.text("Wrong Pin", 0,0)
                        oled.text("Try again", 0,20)
                        oled.show()
                        utime.sleep(0.1)
                        red.value(0)
                        utime.sleep(0.1)
                        red.value(1)
                        utime.sleep(0.1)
                        red.value(0)
                        utime.sleep(0.1)
                        red.value(1)
                        utime.sleep(0.1)
                        red.value(0)
                        utime.sleep(0.1)
                        utime.sleep(1)
                        oled.fill(0)
                        oled.text("Enter pin",0,0)
                        oled.show()
                        cmd = input("Enter pin: ")
                        
                        if cmd == "565":
                            oled.fill(0)
                            oled.show()
                            oled.text("Choose:", 0,0)
                            oled.text("1. Withdrawal", 0,15)
                            oled.text("2. Deposit", 0,30)
                            oled.text("3. Check Balance", 0,45)
                            oled.show()
                            utime.sleep(1)
                            cmd = input("Choose: ")
                            if cmd == "1":
                                print("Enter Amount")
                                oled.fill(0)
                                oled.show()
                                oled.text("Enter Amount:",0,0)
                                oled.show()
                                cmd = input("Amount:")
                                oled.fill(0)
                                oled.show()
                                oled.text(cmd, 0,0)
                                oled.show()
                                utime.sleep(1)
                                if int(cmd) > pb:
                                    oled.fill(0)
                                    yellow.value(1)
                                    oled.show()
                                    oled.text("Insufficient",0,0)
                                    oled.text("balance!", 0,15)
                                    oled.show()
                                    utime.sleep(3)
                                    yellow.value(0)
                                    man_function()
                                else:
                                    oled.fill(0)
                                    pb = pb - int(cmd)
                                    green.value(1)
                                    servo.duty_u16(2887)
                                    utime.sleep(2)
                                    servo.duty_u16(int(4885.68))
                                    green.value(0)
                                    oled.show()
                                    oled.text("Successful!",0,0)
                                    oled.text(cmd + " withdrawn",0,20)
                                    oled.text("Balance:" + str(pb), 0,40)
                                    oled.show()
                                    utime.sleep(3)
                                    man_function()
                            elif cmd == "2":
                                print("Enter Amount")
                                oled.fill(0)
                                oled.show()
                                oled.text("Enter Amount:",0,0)
                                oled.show()
                                cmd = input("Amount:")
                                oled.fill(0)
                                oled.show()
                                oled.text(cmd, 0,0)
                                pb = pb + int(cmd)
                                green.value(1)
                                oled.show()
                                utime.sleep(1)
                                servo.duty_u16(2887)
                                utime.sleep(2)
                                servo.duty_u16(int(4885.68))
                                green.value(0)
                                oled.fill(0)
                                oled.show()
                                oled.text("Successful!",0,0)
                                oled.text(cmd + " Deposited",0,20)
                                oled.text("Balance:" + str(pb), 0,40)
                                oled.show()
                                utime.sleep(3)
                                man_function()
                            elif cmd == "3":
                                print("Your Current Balance: Ksh." + str(pb))
                                oled.fill(0)
                                oled.show()
                                oled.text("Current Balance:", 0,0)
                                oled.text("Ksh." + str(pb), 0,15)
                                oled.show()
                                utime.sleep(3)
                                man_function()
                            
                            else:
                                print("Invalid choice")
                                yellow.value(1)
                                oled.fill(0)
                                oled.show()
                                oled.text("Invalid",0,0)
                                oled.show()
                                utime.sleep(3)
                                yellow.value(0)
                                man_function()
                        else:
                            print("Wrong pin, one attempt!")
                            red.value(1)
                            oled.fill(0)
                            oled.show()
                            oled.text("Wrong Pin", 0,0)
                            oled.text("One attempt", 0,20)
                            oled.show()
                            utime.sleep(0.1)
                            red.value(0)
                            utime.sleep(0.1)
                            red.value(1)
                            utime.sleep(0.1)
                            red.value(0)
                            utime.sleep(0.1)
                            red.value(1)
                            utime.sleep(0.1)
                            red.value(0)
                            utime.sleep(0.1)
                            utime.sleep(1)
                            oled.fill(0)
                            oled.text("Enter Pin",0,0)
                            oled.show()
                            cmd = input("Enter pin: ")
                           
                            if cmd == "565":
                                oled.fill(0)
                                oled.show()
                                oled.text("Choose:", 0,0)
                                oled.text("1. Withdrawal", 0,15)
                                oled.text("2. Deposit", 0,30)
                                oled.text("3. Check Balance", 0,45)
                                oled.show()
                                utime.sleep(1)
                                cmd = input("Choose: ")
                                if cmd == "1":
                                    print("Enter Amount")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Enter Amount:",0,0)
                                    oled.show()
                                    cmd = input("Amount:")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text(cmd, 0,0)
                                    oled.show()
                                    utime.sleep(1)
                                    if int(cmd) > pb:
                                        oled.fill(0)
                                        yellow.value(1)
                                        oled.show()
                                        oled.text("Insufficient",0,0)
                                        oled.text("balance!", 0,15)
                                        oled.show()
                                        utime.sleep(3)
                                        yellow.value(0)
                                        man_function()
                                    else:
                                        oled.fill(0)
                                        pb = pb - int(cmd)
                                        green.value(1)
                                        servo.duty_u16(2887)
                                        utime.sleep(2)
                                        servo.duty_u16(int(4885.68))
                                        green.value(0)
                                        oled.show()
                                        oled.text("Successful!",0,0)
                                        oled.text(cmd + " withdrawn",0,20)
                                        oled.text("Balance:" + str(pb), 0,40)
                                        oled.show()
                                        utime.sleep(3)
                                        man_function()
                                elif cmd == "2":
                                    print("Enter Amount")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Enter Amount:",0,0)
                                    oled.show()
                                    cmd = input("Amount:")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text(cmd, 0,0)
                                    pb = pb + int(cmd)
                                    green.value(1)
                                    servo.duty_u16(2887)
                                    utime.sleep(2)
                                    servo.duty_u16(int(4885.68))
                                    green.value(0)
                                    oled.show()
                                    utime.sleep(1)
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Successful!",0,0)
                                    oled.text(cmd + " Deposited",0,20)
                                    oled.text("Balance:" + str(pb), 0,40)
                                    oled.show()
                                    utime.sleep(3)
                                    man_function()
                                elif cmd == "3":
                                    print("Your Current Balance: Ksh." + str(pb))
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Current Balance:", 0,0)
                                    oled.text("Ksh." + str(pb), 0,15)
                                    oled.show()
                                    utime.sleep(3)
                                    man_function()
                                else:
                                    print("Invalid choice")
                                    yellow.value(1)
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Invalid",0,0)
                                    oled.show()
                                    utime.sleep(3)
                                    yellow.value(0)
                                    man_function()
                                
                            else:
                                print("You have been blocked!")
                                red.value(1)
                                oled.fill(0)
                                oled.show()
                                oled.text("ATM blocked!", 0,0)
                                oled.show()
                                utime.sleep(3)
                                red.value(0)
                                man_function()
                        
            elif card == 412721497:
                print("Hello David Ongachi!")
                oled.fill(0)
                green.value(1)
                oled.show()
                oled.text("Hello David!", 0,0)
                oled.show()
                utime.sleep(1)
                oled.fill(0)
                oled.show()
                oled.text("Enter Pin",0,0)
                oled.show()
                utime.sleep(1)
                green.value(0)
                cmd = input("Enter pin: ")
                
                if cmd == "677":
                    oled.fill(0)
                    oled.show()
                    oled.text("Choose:", 0,0)
                    oled.text("1. Withdrawal", 0,15)
                    oled.text("2. Deposit", 0,30)
                    oled.text("3. Check Balance", 0,45)
                    oled.show()
                    utime.sleep(1)
                    cmd = input("Choose: ")
                    if cmd == "1":
                        print("Enter Amount")
                        oled.fill(0)
                        oled.show()
                        oled.text("Enter Amount:",0,0)
                        oled.show()
                        cmd = input("Amount:")
                        oled.fill(0)
                        oled.show()
                        oled.text(cmd, 0,0)
                        oled.show()
                        utime.sleep(1)
                        if int(cmd) > db:
                            oled.fill(0)
                            yellow.value(1)
                            oled.show()
                            oled.text("Insufficient",0,0)
                            oled.text("balance!", 0,15)
                            oled.show()
                            utime.sleep(3)
                            yellow.value(0)
                            man_function()
                        else:
                            oled.fill(0)
                            db = db - int(cmd)
                            green.value(1)
                            servo.duty_u16(2887)
                            utime.sleep(2)
                            servo.duty_u16(int(4885.68))
                            green.value(0)
                            oled.show()
                            oled.text("Successful!",0,0)
                            oled.text(cmd + " withdrawn",0,20)
                            oled.text("Balance:" + str(db), 0,40)
                            oled.show()
                            utime.sleep(3)
                            man_function()
                        
                    elif cmd == "2":
                        print("Enter Amount")
                        oled.fill(0)
                        oled.show()
                        oled.text("Enter Amount:",0,0)
                        oled.show()
                        cmd = input("Amount:")
                        oled.fill(0)
                        oled.show()
                        oled.text(cmd, 0,0)
                        db = db + int(cmd)
                        green.value(1)
                        servo.duty_u16(2887)
                        utime.sleep(2)
                        servo.duty_u16(int(4885.68))
                        green.value(0)
                        oled.show()
                        utime.sleep(1)
                        oled.fill(0)
                        oled.show()
                        oled.text("Successful!",0,0)
                        oled.text(cmd + " Deposited",0,20)
                        oled.text("Balance:" + str(db), 0,40)
                        oled.show()
                        utime.sleep(3)
                        man_function()
                    elif cmd == "3":
                        print("Your Current Balance: Ksh." + str(db))
                        oled.fill(0)
                        oled.show()
                        oled.text("Current Balance:", 0,0)
                        oled.text("Ksh." + str(db), 0,15)
                        oled.show()
                        utime.sleep(3)
                        man_function()
                    else:
                        print("Invalid choice")
                        yellow.value(1)
                        oled.fill(0)
                        oled.show()
                        oled.text("Invalid",0,0)
                        oled.show()
                        utime.sleep(3)
                        yellow.value(0)
                        man_function()
                else:
                        print("Wrong pin, try again!")
                        red.value(1)
                        oled.fill(0)
                        oled.show()
                        oled.text("Wrong Pin", 0,0)
                        oled.text("Try again", 0,20)
                        oled.show()
                        utime.sleep(0.1)
                        red.value(0)
                        utime.sleep(0.1)
                        red.value(1)
                        utime.sleep(0.1)
                        red.value(0)
                        utime.sleep(0.1)
                        red.value(1)
                        utime.sleep(0.1)
                        red.value(0)
                        utime.sleep(0.1)
                        utime.sleep(1)
                        oled.fill(0)
                        oled.text("Try again",0,0)
                        oled.show()
                        cmd = input("Enter pin: ")
                        p=p+1
                        if cmd == "677":
                            oled.fill(0)
                            oled.show()
                            oled.text("Choose:", 0,0)
                            oled.text("1. Withdrawal", 0,15)
                            oled.text("2. Deposit", 0,30)
                            oled.text("3. Check Balance", 0,45)
                            oled.show()
                            utime.sleep(1)
                            cmd = input("Choose: ")
                            if cmd == "1":
                                print("Enter Amount")
                                oled.fill(0)
                                oled.show()
                                oled.text("Enter Amount:",0,0)
                                oled.show()
                                cmd = input("Amount:")
                                oled.fill(0)
                                oled.show()
                                oled.text(cmd, 0,0)
                                oled.show()
                                utime.sleep(1)
                                if int(cmd) > db:
                                    oled.fill(0)
                                    yellow.value(1)
                                    oled.show()
                                    oled.text("Insufficient",0,0)
                                    oled.text("balance!", 0,15)
                                    oled.show()
                                    utime.sleep(3)
                                    yellow.value(0)
                                    man_function()
                                else:
                                    oled.fill(0)
                                    db = db - int(cmd)
                                    green.value(1)
                                    servo.duty_u16(2887)
                                    utime.sleep(2)
                                    servo.duty_u16(int(4885.68))
                                    green.value(0)
                                    oled.show()
                                    oled.text("Successful!",0,0)
                                    oled.text(cmd + " withdrawn",0,20)
                                    oled.text("Balance:" + str(db), 0,40)
                                    oled.show()
                                    utime.sleep(3)
                                    man_function()
                            elif cmd == "2":
                                print("Enter Amount")
                                oled.fill(0)
                                oled.show()
                                oled.text("Enter Amount:",0,0)
                                oled.show()
                                cmd = input("Amount:")
                                oled.fill(0)
                                oled.show()
                                oled.text(cmd, 0,0)
                                db = db + int(cmd)
                                green.value(1)
                                servo.duty_u16(2887)
                                utime.sleep(2)
                                green.value(0)
                                servo.duty_u16(int(4885.68))
                                oled.show()
                                utime.sleep(1)
                                oled.fill(0)
                                oled.show()
                                oled.text("Successful!",0,0)
                                oled.text(cmd + " Deposited",0,20)
                                oled.text("Balance:" + str(db), 0,40)
                                oled.show()
                                utime.sleep(3)
                                man_function()
                            elif cmd == "3":
                                print("Your Current Balance: Ksh." + str(db))
                                oled.fill(0)
                                oled.show()
                                oled.text("Current Balance:", 0,0)
                                oled.text("Ksh." + str(db), 0,15)
                                oled.show()
                                utime.sleep(3)
                                man_function()
                            else:
                                print("Invalid choice")
                                yellow.value(1)
                                oled.fill(0)
                                oled.show()
                                oled.text("Invalid",0,0)
                                oled.show()
                                utime.sleep(3)
                                yellow.value(0)
                                man_function()
                        else:
                            print("Wrong pin, one attempt!")
                            red.value(1)
                            oled.fill(0)
                            oled.show()
                            oled.text("Wrong Pin", 0,0)
                            oled.text("One attempt", 0,20)
                            oled.show()
                            utime.sleep(0.1)
                            red.value(0)
                            utime.sleep(0.1)
                            red.value(1)
                            utime.sleep(0.1)
                            red.value(0)
                            utime.sleep(0.1)
                            red.value(1)
                            utime.sleep(0.1)
                            red.value(0)
                            utime.sleep(0.1)
                            utime.sleep(1)
                            oled.fill(0)
                            oled.text("Enter Pin",0,0)
                            oled.show()
                            cmd = input("Enter pin: ")
                           
                            if cmd == "677":
                                oled.fill(0)
                                oled.show()
                                oled.text("Choose:", 0,0)
                                oled.text("1. Withdrawal", 0,15)
                                oled.text("2. Deposit", 0,30)
                                oled.text("3. Check Balance", 0,45)
                                oled.show()
                                utime.sleep(1)
                                cmd = input("Choose: ")
                                if cmd == "1":
                                    print("Enter Amount")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Enter Amount:",0,0)
                                    oled.show()
                                    cmd = input("Amount:")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text(cmd, 0,0)
                                    oled.show()
                                    utime.sleep(1)
                                    if int(cmd) > db:
                                        oled.fill(0)
                                        yellow.value(1)
                                        oled.show()
                                        oled.text("Insufficient",0,0)
                                        oled.text("balance!", 0,15)
                                        oled.show()
                                        utime.sleep(3)
                                        yellow.value(0)
                                        man_function()
                                    else:
                                        oled.fill(0)
                                        db = db - int(cmd)
                                        green.value(1)
                                        servo.duty_u16(2887)
                                        utime.sleep(2)
                                        servo.duty_u16(int(4885.68))
                                        green.value(0)
                                        oled.show()
                                        oled.text("Successful!",0,0)
                                        oled.text(cmd + " withdrawn",0,20)
                                        oled.text("Balance:" + str(db), 0,40)
                                        oled.show()
                                        utime.sleep(3)
                                        man_function()
                                elif cmd == "2":
                                    print("Enter Amount")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Enter Amount:",0,0)
                                    oled.show()
                                    cmd = input("Amount:")
                                    oled.fill(0)
                                    oled.show()
                                    oled.text(cmd, 0,0)
                                    green.value(1)
                                    db = db + int(cmd)
                                    servo.duty_u16(2887)
                                    utime.sleep(2)
                                    servo.duty_u16(int(4885.68))
                                    green.value(0)
                                    oled.show()
                                    utime.sleep(1)
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Successful!",0,0)
                                    oled.text(cmd + " Deposited",0,20)
                                    oled.text("Balance:" + str(db), 0,40)
                                    oled.show()
                                    utime.sleep(3)
                                    man_function()
                                elif cmd == "3":
                                    print("Your Current Balance: Ksh." + str(db))
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Current Balance:", 0,0)
                                    oled.text("Ksh." + str(db), 0,15)
                                    oled.show()
                                    utime.sleep(3)
                                    man_function()
                                else:
                                    print("Invalid choice")
                                    yellow.value(1)
                                    oled.fill(0)
                                    oled.show()
                                    oled.text("Invalid",0,0)
                                    oled.show()
                                    utime.sleep(3)
                                    yellow.value(0)
                                    man_function()
                                
                            else:
                                print("You have been blocked!")
                                red.value(1)
                                oled.fill(0)
                                oled.show()
                                oled.text("ATM blocked!", 0,0)
                                oled.show()
                                utime.sleep(3)
                                red.value(0)
                                man_function()
                                
                                
                
            else:
                print("Card invalid!")
                oled.fill(0)
                oled.show()
                oled.text("Card invalid!", 0,0)
                oled.show()
                utime.sleep(0.1)
                red.value(0)
                utime.sleep(0.1)
                red.value(1)
                utime.sleep(0.1)
                red.value(0)
                utime.sleep(0.1)
                red.value(1)
                utime.sleep(0.1)
                red.value(0)
                utime.sleep(0.1)
                utime.sleep(3)
                man_function()
               
    
        
    
                        
    